version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/jossbnd/trainwatch

run:
  timeout: 5m
