services:
  trainwatch-backend:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    env_file:
      - ./.env

  traefik:
    image: traefik:v3.2
    ports:
      - "443:443"
      - "8081:8080"
    volumes:
      - ./docker/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./docker/services.yml:/etc/traefik/services.yml:ro
      - ./docker/certs:/etc/traefik/certs:ro
