http:
  routers:
    trainwatch:
      rule: "Host(`api.trainwatch.app`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: trainwatch

  services:
    trainwatch:
      loadBalancer:
        servers:
          - url: "http://backend:3025"
