http:
  routers:
    trainwatch:
      rule: "Host(`api.localhost`)"
      entryPoints:
        - websecure
      tls: {}
      service: trainwatch

  services:
    trainwatch:
      loadBalancer:
        servers:
          - url: "http://backend:3025"

tls:
  certificates:
    - certFile: /etc/traefik/certs/cert.pem
      keyFile: /etc/traefik/certs/key.pem
